name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Deploy only when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON_PROD }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker to use gcloud as a credential helper
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/$GCP_PROJECT_ID/ship-duniya-image:latest -f Dockerfiles/Dockerfile .

      - name: Push Docker image to Google Container Registry
        run: docker push gcr.io/$GCP_PROJECT_ID/ship-duniya-image:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ship-duniya-service \
            --image=gcr.io/$GCP_PROJECT_ID/ship-duniya-image:latest \
            --region=asia-south1 \
            --platform=managed \
            --allow-unauthenticated
