name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Change this if your main branch has a different name

env:
  GCP_PROJECT_ID: "ship-duniya"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Verify Google Cloud Auth
        run: gcloud auth list

      - name: Check GCP_PROJECT_ID (Debugging)
        run: echo "GCP_PROJECT_ID=${{ secrets.GCP_PROJECT_ID }}"

      - name: Build Docker Image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/ship-duniya-image:latest -f Dockerfiles/Dockerfile .
      
      - name: Push Docker Image to Google Container Registry
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/ship-duniya-image:latest

      - name: Deploy to Google Cloud Run
        run: gcloud run deploy ship-duniya-service \
          --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/ship-duniya-image:latest \
          --region=asia-south1 \
          --platform=managed \
          --allow-unauthenticated
